version: '3'
services:
  my-app:
   image: my-app:1.0
   ports:
    - 3000:3000
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongodata:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-exp
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongodata:
networks:
  backend:
    driver: "bridge"
